events {
    worker_connections 1024;
}

http {
    upstream fastapi_app {
        # round-robin
        server fastapi_web1:8000;
        server fastapi_web2:8000;
    }

    # Redirect traffic to HTTPS
    server {
        listen 80;
        server_name fraud-detection-myapi.duckdns.org;

        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Serve HTTPS
    server {
        listen 443 ssl;
        server_name fraud-detection-myapi.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/fraud-detection-myapi.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/fraud-detection-myapi.duckdns.org/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://fastapi_app;
            # preserve client details
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}