import os

API_PREFIX = "/api/v1"
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CACHE_TTL_SECONDS = 3600
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_URL = os.getenv("CELERY_RESULT_URL", REDIS_URL)